steps:
- name: gcr.io/cloud-builders/git
  args: ['fetch', '--unshallow']
- name: 'eu.gcr.io/$PROJECT_ID/hmf-icgc-image-builder:latest'
  args: ['mvn', '-pl', 'dcc-portal-server', '-Dmaven.test.skip=true']
  id: mvn
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'dcc-portal-server/Dockerfile', '-t', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME-server:$SHORT_SHA', 'dcc-portal-server/']
  waitFor: ['mvn']
images: ['eu.gcr.io/$PROJECT_ID/$REPO_NAME-server']
timeout: 2400s
